export { default as Navbar } from './Navbar';
export { default as Logo } from './Logo';
export { default as HeroSection } from './HeroSection';
export { default as ServicesSection } from './ServicesSection';
export { default as ITServicesSection } from './ITServicesSection';
export { default as InsightsSection } from './InsightsSection';
export { default as ProjectsSection } from './ProjectsSection';
export { default as CTASection } from './CTASection';
export { default as Footer } from './Footer';
